---
name: Test Repairs
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --frozen
      - run: uv run --frozen python -m unittest discover -s tests -p 'test_repair*.py'
